// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTfLUvW4VaId1EI3dX-EQtdlXMQaX98ks',
    appId: '1:304537071514:web:a027629566ac3df6081423',
    messagingSenderId: '304537071514',
    projectId: 'studymate-c088f',
    authDomain: 'studymate-c088f.firebaseapp.com',
    storageBucket: 'studymate-c088f.firebasestorage.app',
    measurementId: 'G-LTD92JYM1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXVlGyiAxGMo-KdABJvFfSQHZf43C5eCs',
    appId: '1:304537071514:android:49fe89c253bbd5e5081423',
    messagingSenderId: '304537071514',
    projectId: 'studymate-c088f',
    storageBucket: 'studymate-c088f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBubWfQd6DViTCU_7Ym1SoAvO62vu6Q3U0',
    appId: '1:304537071514:ios:51ef27d233d71392081423',
    messagingSenderId: '304537071514',
    projectId: 'studymate-c088f',
    storageBucket: 'studymate-c088f.firebasestorage.app',
    iosBundleId: 'com.example.studymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBubWfQd6DViTCU_7Ym1SoAvO62vu6Q3U0',
    appId: '1:304537071514:ios:51ef27d233d71392081423',
    messagingSenderId: '304537071514',
    projectId: 'studymate-c088f',
    storageBucket: 'studymate-c088f.firebasestorage.app',
    iosBundleId: 'com.example.studymate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTfLUvW4VaId1EI3dX-EQtdlXMQaX98ks',
    appId: '1:304537071514:web:a8652d3a4167442c081423',
    messagingSenderId: '304537071514',
    projectId: 'studymate-c088f',
    authDomain: 'studymate-c088f.firebaseapp.com',
    storageBucket: 'studymate-c088f.firebasestorage.app',
    measurementId: 'G-8WZYHWFM7L',
  );
}
